.\" 
.\"									
.\"	Copyright (c) 1987,1988,1989,1990,1991,1992   AT&T		
.\"			All Rights Reserved				
.\"									
.\"	  THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T.		
.\"	    The copyright notice above does not evidence any		
.\"	   actual or intended publication of such source code.		
.\"									
.\" 
.ds ZZ APPLICATION DEVELOPMENT PACKAGE
.TH ADDR 3R
.XE "addr()"
.SH NAME
addr \- return the Word address of a Point in a Bitmap
.SH SYNOPSIS
\f3
Word *addr (b, p)
.sp
.B Bitmap *b;
.br
.B Point p;\fR
.SH DESCRIPTION
The
.I addr 
function
returns the address of the Word containing the bit
corresponding to the Point
.I p
in the Bitmap
.I b.
.SH EXAMPLE
The following subroutine can be used to determine whether a Point
.I p
in a Bitmap
.I b
is on or off (returning 1 or 0, respectively).
.PP
.RS 3
.nf
.ft CM
#include <dmd.h>

pixel (b, p)
Bitmap *b;
Point	p;
{
	Word *w;
	unsigned int bit;

	w = addr (b, p);
	bit = FIRSTBIT >> (p.x%WORDSIZE);
	return (*w&bit)==bit;
}
.fi
.ft R
.RE
.PP
This routine is implemented differently in \f2rol\f1(3L).
.SH SEE ALSO
rol(3L).
