.\" 
.\"									
.\"	Copyright (c) 1987,1988,1989,1990,1991,1992   AT&T		
.\"			All Rights Reserved				
.\"									
.\"	  THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T.		
.\"	    The copyright notice above does not evidence any		
.\"	   actual or intended publication of such source code.		
.\"									
.\" 
.ds ZZ APPLICATION DEVELOPMENT PACKAGE
.TH EXIT 3R
.XE "exit()"
.SH NAME
exit \- cease execution
.SH SYNOPSIS
.B void exit( );
.SH DESCRIPTION
The
.I exit
function
terminates a process.
In either the 
.I stand-alone
or
.I layers
world, calling
.I exit
replaces the running process by the default terminal program.
Any associated \s-1UNIX\s+1 system process must
be terminated separately,
since
.I exit
is a purely local function.
When a process calls
.IR exit ,
all local resources: keyboard, mouse, storage, etc.,
are deallocated automatically.
.SH EXAMPLE
.RS 3
.ft CM
.nf
#include <dmd.h>

main()
{
     char c;
 
     request (KBD);
 
     .
     .
 
     if ( (c = kbdchar()) == 'q')
             exit();
     .
     .

}
.fi
.ft R
.RE
