.\" 
.\"									
.\"	Copyright (c) 1987,1988,1989,1990,1991,1992   AT&T		
.\"			All Rights Reserved				
.\"									
.\"	  THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T.		
.\"	    The copyright notice above does not evidence any		
.\"	   actual or intended publication of such source code.		
.\"									
.\" 
.ds ZZ APPLICATION DEVELOPMENT PACKAGE
.TH JELLIPSE 3L
.XE "jellipse()"
.XE "jeldisc()"
.XE "jelarc()"
.SH NAME
jellipse, jeldisc, jelarc \- draw ellipse on display
.SH SYNOPSIS
.B void jellipse(p, a, b, f)
.PP
.B void jeldisc(p, a, b, f)
.PP
\fBvoid jelarc(p, a, b, p1, p2, f)\fR
.PP
.B Point p, p1, p2;
.br
.B int a, b;
.br
.B Code f;
.SH DESCRIPTION
The
.I jellipse
function
draws in the Bitmap
display
an approximate ellipse centered at
.IR p ,
with horizontal semi-axis
.I a
and vertical semi-axis
.I b
with Code
.IR  f .
.PP
The
.I jeldisc
function
draws in the Bitmap display an elliptical disc centered at
.IR p ,
with horizontal semi-axis
.I a
and vertical semi-axis
.I b
with Code
.IR f .
.PP
The
.I jelarc
function
draws the corresponding elliptical arc,
centered at
.IR p ,
counterclockwise from the ellipse point closest to
.I p1
to the ellipse point closest to
.I p2
with Code
.IR f .
.PP
All coordinates and semi-axes are in layer coordinates.
.SH EXAMPLE
The following routine draws a row of six ellipses,
a row of six discs, and a row of six arcs, scaled
to the shape of the layer.
.PP
.RS 3
.ft CM
.nf
#include <dmd.h>

draw()
{
  Point p;
  int i, r;

  request (MOUSE|KBD);
  r = 50;
  p.y = 200;
  for ( p.x=100; p.x < XMAX-50; p.x+=120)
       jellipse (p, r, r-25, F_XOR);
  p.y = 600;
  for ( p.x=100; p.x < XMAX-50; p.x+=120)
       jeldisc (p, r-25, r, F_XOR);
  p.y = 900;
  for (p.x=100; p.x < XMAX-50; p.x+=120)
       jelarc (p, r, r, Pt(p.x-r, p.y),
               Pt(p.x+r, p.y), F_XOR);
}
.fi
.RE
.ft R
.SH SEE ALSO
circle(3L), ellipse(3L), jcircle(3L).
