.\" 
.\"									
.\"	Copyright (c) 1987,1988,1989,1990,1991,1992   AT&T		
.\"			All Rights Reserved				
.\"									
.\"	  THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T.		
.\"	    The copyright notice above does not evidence any		
.\"	   actual or intended publication of such source code.		
.\"									
.\" 
.ds ZZ APPLICATION DEVELOPMENT PACKAGE
.TH JSTRING 3R
.XE "jstring()"
.SH NAME
jstring \- draw character string on display
.SH SYNOPSIS
.B Point jstring(s)
.PP
.B char *s;
.SH DESCRIPTION
The
.I jstring
function
draws, in the \s-1F_XOR\s+1 mode,
the null-terminated string
.I s
in the display Bitmap 
so that the origin
of the rectangle enclosing the first character is at the current point.
It returns the current point, which is left after the last character
of the string, so adjacent calls to 
.I jstring
can appear to concatenate their argument strings on the screen.
.SH EXAMPLE
The following routine shows how \fIjstring\fR automatically updates
.IR PtCurrent .
.PP
.RS 3
.ft CM
.nf
#include <dmd.h>

main()
{
    jmove (Pt(16,16));
    jstring ("I");
    jline (Pt(40,0), F_XOR);
    jstring ("love");
    jline (Pt(40,0), F_XOR);
    jstring ("my");
    jline (Pt(40,0), F_XOR);
    jstring ("DMD");

    request (KBD);
    wait (KBD);
}
.fi
.ft R
.RE
.SH SEE ALSO
string(3R).
