.\" 
.\"									
.\"	Copyright (c) 1987,1988,1989,1990,1991,1992   AT&T		
.\"			All Rights Reserved				
.\"									
.\"	  THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T.		
.\"	    The copyright notice above does not evidence any		
.\"	   actual or intended publication of such source code.		
.\"									
.\" 
.ds ZZ APPLICATION DEVELOPMENT PACKAGE
.TH NORM 3L
.SH NAME
norm, sqrtryz \- return norm or coordinate of three-dimensional vector
.SH SYNOPSIS
\f3int norm (x, y, z)
.sp
int sqrtryz (r, y, z)
.sp
int r, x, y, z;
\f1
.SH DESCRIPTION
The
.I norm
utility returns the norm of the vector
.RI ( "x, y, z" ).
It is defined by the equation:
.sp
.RS 10
.EQ
sqrt {x sup 2 + y sup 2 + z sup 2}
.EN
.sp
.RE
The
.I sqrtryz
call returns the x-coordinate when passed the norm
.I r
and
.IR y " and " z
coordinates.
It is defined by the equation:
.sp
.RS 10
.EQ
sqrt{r sup 2 - y sup 2 - z sup 2}
.EN
.RE
