.\" 
.\"									
.\"	Copyright (c) 1987,1988,1989,1990,1991,1992   AT&T		
.\"			All Rights Reserved				
.\"									
.\"	  THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T.		
.\"	    The copyright notice above does not evidence any		
.\"	   actual or intended publication of such source code.		
.\"									
.\" 
.ds ZZ APPLICATION DEVELOPMENT PACKAGE
.TH POINT 3R
.XE "point()"
.SH NAME
point \- draw a single pixel in a Bitmap
.SH SYNOPSIS
.ft B
void point (b, p, f)
.sp
Bitmap *b;
.br
Point p;
.br
Code f;
.SH DESCRIPTION
The
.I point
function
draws the pixel at Point
.I p
in the Bitmap
.I b
according to function Code
.IR f .
.SH EXAMPLE
The following routine determines the Point at the middle of
the layer, draws and then returns it.
.PP
.RS 3
.nf
.ft CM
#include <dmd.h>

Point middle()
{
	Point center, offset;

	offset = div (sub (Drect.corner,
		Drect.origin), 2);
	center = add (Drect.origin, offset);
	point (&display, center, F_XOR);
	return center;
}
\fR
.fi
.RE
.SH SEE ALSO
jpoint(3R).
