.\" 
.\"									
.\"	Copyright (c) 1987,1988,1989,1990,1991,1992   AT&T		
.\"			All Rights Reserved				
.\"									
.\"	  THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T.		
.\"	    The copyright notice above does not evidence any		
.\"	   actual or intended publication of such source code.		
.\"									
.\" 
.ds ZZ APPLICATION DEVELOPMENT PACKAGE
.TH PTINRECT 3R
.SH NAME
ptinrect \- check for Point inclusion in a Rectangle
.SH SYNOPSIS
.ft B
int ptinrect(p, r)
.sp
Point p;
.br
Rectangle r;
.SH DESCRIPTION
The
.I ptinrect 
function
returns 1 if
.I p
is a Point within Rectangle
.I r
and 0 otherwise.
.SH EXAMPLE
The following routine will draw a box in the middle of a layer.
Then when the user hits button 1,
the bell will ring.
The routine exits when a key is typed.
.PP
.RS 3
.nf
.ft CM
\s-1
#include <dmd.h>

ringbox()
{
   Point center, offset;
   Rectangle midbox;

   offset = div (sub (Drect.corner,
                Drect.origin), 2);
   center = add (Drect.origin, offset);
   midbox.origin = sub (center, Pt (16, 16));
   midbox.corner = add (center, Pt (16, 16));
   outline (midbox);
   request (MOUSE|KBD);
   while (kbdchar () == -1){
   	wait (MOUSE);
   	if (ptinrect (mouse.xy, midbox) &&
             button1()) ringbell();
   }
}
\fR
.fi
.RE
\s+1
