.\" 
.\"									
.\"	Copyright (c) 1987,1988,1989,1990,1991,1992   AT&T		
.\"			All Rights Reserved				
.\"									
.\"	  THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T.		
.\"	    The copyright notice above does not evidence any		
.\"	   actual or intended publication of such source code.		
.\"									
.\" 
.ds ZZ APPLICATION DEVELOPMENT PACKAGE
.TH RINGBELL 3R
.XE "ringbell()"
.SH NAME
ringbell \- ring the \s-1DMD\s+1 bell
.SH SYNOPSIS
.ft B
void ringbell ( )
.ft R
.SH DESCRIPTION
This function rings the bell on the \s-1DMD\s+1.
.SH EXAMPLE
See the example in
.IR polygon (3R).
.SH SEE ALSO
polygon(3R).
