.\" 
.\"									
.\"	Copyright (c) 1987,1988,1989,1990,1991,1992   AT&T		
.\"			All Rights Reserved				
.\"									
.\"	  THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T.		
.\"	    The copyright notice above does not evidence any		
.\"	   actual or intended publication of such source code.		
.\"									
.\" 
.ds ZZ APPLICATION DEVELOPMENT PACKAGE
.TH TEXTURE 3R
.XE "texture()"
.XE "T_grey"
.XE "T_lightgrey"
.XE "T_darkgrey"
.XE "T_black"
.XE "T_white"
.XE "T_checks"
.XE "T_background"
.SH NAME  
texture \- draw Texture in Rectangle in Bitmap
.SH SYNOPSIS
.ft B
void texture (b, r, t, f)
.sp .5
Bitmap *b; 
.br 
Rectangle r;
.br 
Texture *t; 
.br 
Code f;
.sp .5
Texture T_grey, T_lightgrey, T_darkgrey;
.sp .5
Texture T_black, T_white, T_background, T_checks;
.SH DESCRIPTION
The
.I texture
function
draws the Texture specified by
.I t
with function Code
.I f
in the Rectangle
.I r
in the Bitmap
.IR b .
The Textures listed above are in \s-1ROM\s+1 and are accessible with
the above names.
.SH EXAMPLE
The following routine allows doodling with a Texture.
.PP
.RS 3
.nf
.ft CM
#include <dmd.h>
main()
{
	Rectangle r;
	Point s;
	s.x = 16;
	s.y = 16;
	request (MOUSE);
	for (wait(MOUSE); !button3();
		wait(MOUSE)){
		r.origin = mouse.xy;
		r.corner = add (r.origin, s);
		if( button1() )
			texture (&display, r,
				&T_grey, F_STORE);
		if( button2() )
			texture (&display, r,
				&T_grey, F_CLR);
	}
}
\fR
.fi
.RE
.SH SEE ALSO
jtexture(3R), structures(3R), texture16(3L).
